### ISSUE TITLE
Create Placement Schedule Card Component

### ISSUE THREAD

**Issue by Doraemon012** [Doraemon012/Fusion-client#2]
### **Description:**  
Implement the placement schedule card component using Mantine’s Card component. 

### **Additional Context:**  
- [Mantine Card](https://mantine.dev/core/card/)
- [Figma Design](https://www.figma.com/design/BxVeA6U4Hwav5EHUctzV5O/Placement-Cell-Assignment-5?node-id=39-19)

### **Screenshots:**  
![image](https://github.com/user-attachments/assets/0c3d34ae-dca1-4063-a689-4955dd7e4efc)

**Comment by sam2104** [comment]
done
