### ISSUE TITLE
Create the Stasticts table Component

### ISSUE THREAD

**Issue by Doraemon012** [Doraemon012/Fusion-client#4]
### **Description:**  
Create the statistics table using Mantine’s Table component. The table should be responsive. 
Display a fixed number of rows at a time (eg. 20) and have pagination as shown in the image.

### **Additional Context:**  
- [Mantine Table](https://mantine.dev/core/table/) for creating tables.

### **Screenshots:**  
![image](https://github.com/user-attachments/assets/9b5d84e3-d96c-4594-bba6-a3b8133ce99d)

**Comment by sam2104** [comment]
assign me to this
