### ISSUE TITLE
Create the Application Status Timeline Component

### ISSUE THREAD

**Issue by Doraemon012** [Doraemon012/Fusion-client#6]
### **Description:**  
Build the application status timeline component using Mantine’s Timeline component to visually represent the stages of a student’s application. Ensure the timeline follows the dashboard’s color scheme and is responsive across devices.

### **Additional Context:**  
- [Mantine Timeline](https://mantine.dev/core/timeline/) for a responsive and visually appealing timeline component.

### **Screenshots:**  
![image](https://github.com/user-attachments/assets/bfb71f6f-01a6-42f8-ad63-ea14898ed033)

**Comment by sam2104** [comment]
assign me

**Comment by sam2104** [comment]
done
