### ISSUE TITLE
Create the add placememnt event form

### ISSUE THREAD

**Issue by Doraemon012** [Doraemon012/Fusion-client#7]
### **Description:**  
Create the add placement event form for tpo using Mantine’s Form component. 

### **Additional Context:**  
- [Mantine Forms](https://mantine.dev/form/use-form/) for managing the form state.
- [FIgma UI](https://www.figma.com/design/BxVeA6U4Hwav5EHUctzV5O/Placement-Cell-Assignment-5?node-id=0-1)

### **Screenshots:**  

![image](https://github.com/user-attachments/assets/e13849c8-80a2-4a82-9431-0d8d604c762e)

**Comment by sam2104** [comment]
done
