### ISSUE TITLE
Create the add placement record form 

### ISSUE THREAD

**Issue by Doraemon012** [Doraemon012/Fusion-client#8]
### Description:

Create the add placement record form for tpo using Mantine’s Form component.
### Additional Context:

- [Mantine Forms](https://mantine.dev/form/use-form/) for managing the form state.
- [FIgma UI](https://www.figma.com/design/BxVeA6U4Hwav5EHUctzV5O/Placement-Cell-Assignment-5?node-id=0-1)

### Screenshots

![image](https://github.com/user-attachments/assets/250ccab6-e864-41a3-a179-30c08d7314c8)

**Comment by sam2104** [comment]
done
